application: exampwedding
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /resources
  static_dir: resources

- url: /.*
  script: main.app
  
libraries:
- name: jinja2
  version: latest